/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WingTschunRouteImport } from './routes/wing-tschun'
import { Route as WarsteinRouteImport } from './routes/warstein'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TrainingsinhalteRouteImport } from './routes/trainingsinhalte'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SchulenRouteImport } from './routes/schulen'
import { Route as PrinzipienRouteImport } from './routes/prinzipien'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as HammRouteImport } from './routes/hamm'
import { Route as ErwitteRouteImport } from './routes/erwitte'
import { Route as EinsteigerRouteImport } from './routes/einsteiger'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'

const WingTschunRoute = WingTschunRouteImport.update({
  id: '/wing-tschun',
  path: '/wing-tschun',
  getParentRoute: () => rootRouteImport,
} as any)
const WarsteinRoute = WarsteinRouteImport.update({
  id: '/warstein',
  path: '/warstein',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingsinhalteRoute = TrainingsinhalteRouteImport.update({
  id: '/trainingsinhalte',
  path: '/trainingsinhalte',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SchulenRoute = SchulenRouteImport.update({
  id: '/schulen',
  path: '/schulen',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinzipienRoute = PrinzipienRouteImport.update({
  id: '/prinzipien',
  path: '/prinzipien',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const HammRoute = HammRouteImport.update({
  id: '/hamm',
  path: '/hamm',
  getParentRoute: () => rootRouteImport,
} as any)
const ErwitteRoute = ErwitteRouteImport.update({
  id: '/erwitte',
  path: '/erwitte',
  getParentRoute: () => rootRouteImport,
} as any)
const EinsteigerRoute = EinsteigerRouteImport.update({
  id: '/einsteiger',
  path: '/einsteiger',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/einsteiger': typeof EinsteigerRoute
  '/erwitte': typeof ErwitteRoute
  '/hamm': typeof HammRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/prinzipien': typeof PrinzipienRoute
  '/schulen': typeof SchulenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/training': typeof TrainingRoute
  '/trainingsinhalte': typeof TrainingsinhalteRoute
  '/videos': typeof VideosRoute
  '/warstein': typeof WarsteinRoute
  '/wing-tschun': typeof WingTschunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/einsteiger': typeof EinsteigerRoute
  '/erwitte': typeof ErwitteRoute
  '/hamm': typeof HammRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/prinzipien': typeof PrinzipienRoute
  '/schulen': typeof SchulenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/training': typeof TrainingRoute
  '/trainingsinhalte': typeof TrainingsinhalteRoute
  '/videos': typeof VideosRoute
  '/warstein': typeof WarsteinRoute
  '/wing-tschun': typeof WingTschunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/einsteiger': typeof EinsteigerRoute
  '/erwitte': typeof ErwitteRoute
  '/hamm': typeof HammRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/prinzipien': typeof PrinzipienRoute
  '/schulen': typeof SchulenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/training': typeof TrainingRoute
  '/trainingsinhalte': typeof TrainingsinhalteRoute
  '/videos': typeof VideosRoute
  '/warstein': typeof WarsteinRoute
  '/wing-tschun': typeof WingTschunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/einsteiger'
    | '/erwitte'
    | '/hamm'
    | '/impressum'
    | '/kontakt'
    | '/prinzipien'
    | '/schulen'
    | '/sitemap.xml'
    | '/training'
    | '/trainingsinhalte'
    | '/videos'
    | '/warstein'
    | '/wing-tschun'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/einsteiger'
    | '/erwitte'
    | '/hamm'
    | '/impressum'
    | '/kontakt'
    | '/prinzipien'
    | '/schulen'
    | '/sitemap.xml'
    | '/training'
    | '/trainingsinhalte'
    | '/videos'
    | '/warstein'
    | '/wing-tschun'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/einsteiger'
    | '/erwitte'
    | '/hamm'
    | '/impressum'
    | '/kontakt'
    | '/prinzipien'
    | '/schulen'
    | '/sitemap.xml'
    | '/training'
    | '/trainingsinhalte'
    | '/videos'
    | '/warstein'
    | '/wing-tschun'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  EinsteigerRoute: typeof EinsteigerRoute
  ErwitteRoute: typeof ErwitteRoute
  HammRoute: typeof HammRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  PrinzipienRoute: typeof PrinzipienRoute
  SchulenRoute: typeof SchulenRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrainingRoute: typeof TrainingRoute
  TrainingsinhalteRoute: typeof TrainingsinhalteRoute
  VideosRoute: typeof VideosRoute
  WarsteinRoute: typeof WarsteinRoute
  WingTschunRoute: typeof WingTschunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wing-tschun': {
      id: '/wing-tschun'
      path: '/wing-tschun'
      fullPath: '/wing-tschun'
      preLoaderRoute: typeof WingTschunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warstein': {
      id: '/warstein'
      path: '/warstein'
      fullPath: '/warstein'
      preLoaderRoute: typeof WarsteinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainingsinhalte': {
      id: '/trainingsinhalte'
      path: '/trainingsinhalte'
      fullPath: '/trainingsinhalte'
      preLoaderRoute: typeof TrainingsinhalteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schulen': {
      id: '/schulen'
      path: '/schulen'
      fullPath: '/schulen'
      preLoaderRoute: typeof SchulenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prinzipien': {
      id: '/prinzipien'
      path: '/prinzipien'
      fullPath: '/prinzipien'
      preLoaderRoute: typeof PrinzipienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hamm': {
      id: '/hamm'
      path: '/hamm'
      fullPath: '/hamm'
      preLoaderRoute: typeof HammRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erwitte': {
      id: '/erwitte'
      path: '/erwitte'
      fullPath: '/erwitte'
      preLoaderRoute: typeof ErwitteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einsteiger': {
      id: '/einsteiger'
      path: '/einsteiger'
      fullPath: '/einsteiger'
      preLoaderRoute: typeof EinsteigerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  EinsteigerRoute: EinsteigerRoute,
  ErwitteRoute: ErwitteRoute,
  HammRoute: HammRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  PrinzipienRoute: PrinzipienRoute,
  SchulenRoute: SchulenRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrainingRoute: TrainingRoute,
  TrainingsinhalteRoute: TrainingsinhalteRoute,
  VideosRoute: VideosRoute,
  WarsteinRoute: WarsteinRoute,
  WingTschunRoute: WingTschunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
